fix(preview): fix other file preview error problem
Molunerfinn/PicGo pull request #1051
Opened 2022-12-28 11:17 UTC by mouyong

1. display filename
2. remove img element when img load error

close #1050

2022-12-28 11:27 UTC, Molunerfinn requested changes

2022-12-28 11:27 UTC, Molunerfinn commented on src/renderer/pages/Gallery.vue
> +              <span>{{ item.fileName }}</span>
文本过长时需要省略号

2022-12-29 00:57 UTC, mouyong commented on src/renderer/pages/Gallery.vue
> +              <span>{{ item.fileName }}</span>
yarn dev 看不到运行效果，你方便改一下吗

2022-12-29 01:06 UTC, Molunerfinn commented
我回头自行处理吧。

2022-12-29 01:06 UTC, closed without merging

2022-12-30 04:01 UTC, mouyong commented
好的，谢谢，处理好了可以和我说一声吗，我更新应用程序

2022-12-30 04:20 UTC, Molunerfinn commented
可以的，会在issue里跟你说明。