:sparkles: Feature: 为Ubuntu系统适配桌面图标栏（Tray）
Molunerfinn/PicGo pull request #603
Opened 2020-12-27 21:56 UTC by lpypl

2020-12-28 01:53 UTC, Molunerfinn requested changes

2020-12-28 01:53 UTC, Molunerfinn commented on src/main/apis/app/system/index.ts
> +    const submenu = picBeds.filter(item => item.visible).map(item => {
既然linux不需要submenu，那这里也没必要初始化了。

2020-12-28 01:53 UTC, Molunerfinn commented on src/main/apis/app/system/index.ts
> +  else if (process.platform === "linux") {
这个地方判断的逻辑其实就少了submenu而已，没必要做个大判断，重复代码太多，只要在MenuItem里做判断就行。

2020-12-28 01:53 UTC, Molunerfinn commented on src/main/apis/app/system/index.ts
> -  tray.on('drop-files', async (event: Event, files: string[]) => {
mac上的拖拽tray上传为啥给删掉了？

2020-12-28 01:53 UTC, Molunerfinn commented on src/main/lifeCycle/index.ts
> +      if (process.platform === 'darwin' || process.platform === 'win32' || process.platform === "linux") {
如果全平台都要createTray，这里不需要判断了。

2020-12-28 01:53 UTC, Molunerfinn commented on src/main/apis/app/system/index.ts
> +  else if (process.platform === "linux") {
这个else if没看懂，上面的eles已经会走进去打开setting窗口，这里再打开一个菜单？

2020-12-28 02:28 UTC, lpypl commented on src/main/apis/app/system/index.ts
> +  else if (process.platform === "linux") {
整体结构是这样的，把mac/windwos和linux区分开是因为linux（现在确定的是Unity桌面环境）中的Tray不支持click事件，需要在一开始就设置好菜单，而Mac和Windows按照原先策略在点击时创建
```
  if (process.platform === "darwin" || process.platform === "win32") {
  ......
  } 
  // click事件在Ubuntu上无法触发，Unity不支持（在Mac和Windows上可以触发）
  // 需要使用 setContextMenu 设置菜单
  else if (process.platform === "linux") {
    createContextMenu()
    tray!.setContextMenu(contextMenu)
  }
```

2020-12-28 02:47 UTC, lpypl commented on src/main/apis/app/system/index.ts
> +  else if (process.platform === "linux") {
这个地方分开有三方面考虑：
1. 在linux上tray的ContextMenu主要用于唤醒应用和退出（因为不支持click事件，也就无法在click时打开主界面），有必要对一些选项顺序作出调整，比如打开主窗口放第一个，退出应用放最后一个
2. 原先菜单中有些无法按照原先逻辑实现，也是由于Linux上tray的局限性，暂未实现
3. 为了适配Ubuntu，一些选单有微小调整![](https://cdn.jsdelivr.net/gh/lpypl/picgo-repo/data/20201228104412.png)

不过即使仅保留打开主窗口功能和退出应用这样的功能对于Linux平台上PicGo的使用也能带来很大的体验提升。如果只使用快捷键就可以隐藏掉MiniWindow，而仍然使其保留在tray栏，既不影响桌面显示，又可以随时从Tray打开主界面和MiniWindow，我再更新一个版本，删掉多余代码

2020-12-28 02:54 UTC, Molunerfinn commented on src/main/apis/app/system/index.ts
> +  else if (process.platform === "linux") {
OK

2020-12-28 03:01 UTC, lpypl commented on src/main/lifeCycle/index.ts
> +      if (process.platform === 'darwin' || process.platform === 'win32' || process.platform === "linux") {
也许可以保留，毕竟process.platform的可选值不止这三个（比如freebsd），这样也没什么大问题，看起来也清晰点

2020-12-28 03:06 UTC, Molunerfinn commented on src/main/lifeCycle/index.ts
> +      if (process.platform === 'darwin' || process.platform === 'win32' || process.platform === "linux") {
> 也许可以保留，毕竟process.platform的可选值不止这三个（比如freebsd），这样也没什么大问题，看起来也清晰点

不过picgo的构建产物里只有这三个平台...

2020-12-28 03:30 UTC, lpypl commented on src/main/apis/app/system/index.ts
> -  tray.on('drop-files', async (event: Event, files: string[]) => {
误删，已经添加

2020-12-28 03:30 UTC, lpypl commented on src/main/lifeCycle/index.ts
> +      if (process.platform === 'darwin' || process.platform === 'win32' || process.platform === "linux") {
OK，已更新

2020-12-28 03:50 UTC, lpypl commented
更新：
1. 去除`if (process.platform === 'darwin' || process.platform === 'win32' || process.platform === "linux") `等无效代码
2. 重新添加误删的适用于Mac的Tray拖拽相关操作代码

2020-12-28 04:07 UTC, Molunerfinn commented
下班后有时间看看，不要催哈

2020-12-28 05:50 UTC, lpypl commented
经测试，在Manjaro+i3桌面环境下Tray表现正常

2020-12-29 01:59 UTC, Molunerfinn approved these changes

2020-12-29 01:59 UTC, merged